from __future__ import annotations
from pathlib import Path
import tempfile,unittest
from tools.otbm_atlas.viewer import write_viewer
class ViewerTests(unittest.TestCase):
	def test_static_viewer_exposes_navigation_and_required_overlays(self)->None:
		with tempfile.TemporaryDirectory() as directory:
			text=write_viewer(directory).read_text(encoding="utf-8");self.assertTrue((Path(directory)/"viewer-runtime.js").is_file());self.assertTrue((Path(directory)/"viewer-app.js").is_file());self.assertTrue((Path(directory)/"creature-animation-runtime.js").is_file());self.assertFalse((Path(directory)/"data/environment-animations/index.json").exists())
		for marker in ("actionIds","uniqueIds","teleports","houseDoors","monsterSpawns","npcSpawns","Jump","Search world","details","tooltip","X,Y,Z"):self.assertIn(marker,text)
		for marker in ("Render mode","Auto","Detailed","Performance","Diagnostics"):self.assertIn(marker,text)
		self.assertIn('creature-animation-runtime.js',text);self.assertIn('min="0" max="15"',text);self.assertNotIn('min="-8" max="7"',text);app=(Path(__file__).parents[1]/"viewer_app.js").read_text(encoding="utf-8");runtime=(Path(__file__).parents[1]/"viewer_runtime.js").read_text(encoding="utf-8");creature_runtime=(Path(__file__).parents[1]/"creature_animation_runtime.js").read_text(encoding="utf-8");self.assertIn("Number.isInteger(requestedZ)",app);self.assertIn("displayFloor=z=>z",app);self.assertNotIn("displayFloor=z=>7-z",app);self.assertIn("state.overlays=[...state.overlays,item.kind]",app);self.assertIn("if(target)showDetails(item.kind,target)",app);self.assertIn("for(const kind of state.overlays)",app);self.assertIn("parseCoordinateSearch",app);self.assertIn("showTooltip",app);self.assertIn("drawCreatureSprite",app);self.assertNotIn("drawNpcSprite",app);self.assertIn("CREATURE_KINDS",app);self.assertIn("'monsterSpawns'",app);self.assertIn("record.sprite",app);self.assertIn("if(record.spriteAnimation)return true",app);self.assertIn("state.zoom<.25&&(kind==='monsterSpawns'||kind==='supplementalMonsterSpawns')",app);self.assertIn("supplementalNpcSpawns",runtime);self.assertIn("supplementalMonsterSpawns",runtime);self.assertIn("p.has('z')&&Number.isFinite(+p.get('z'))?+p.get('z'):7",runtime);self.assertIn("CREATURE_ANIMATION_SCALE=.45",creature_runtime);self.assertIn("creatureAnimationSelection",creature_runtime);self.assertIn("new BoundedLRU(128,4*1024*1024)",creature_runtime);self.assertIn("record.spriteAnimation",creature_runtime)
if __name__=="__main__":unittest.main()
