import {BoundedLRU,baseLayer,parseViewState,persistMode,viewUrl,visibleChunks} from './viewer-runtime.js';
const $=s=>document.querySelector(s),canvas=$('#map'),ctx=canvas.getContext('2d'),status=$('#status'),floorSelect=$('#floor'),modeSelect=$('#renderMode'),diagnostics=$('#diagnostics'),details=$('#details');
const storedLayers=JSON.parse(localStorage.getItem('otheryn.atlas.layers')||'[]');let state=parseViewState(location.href,{x:32360,y:32230,z:7,zoom:.18,renderMode:localStorage.getItem('otheryn.atlas.renderMode')||'auto',overlays:storedLayers,selectedMarker:null});
let manifest,chunks=[],drag=null,searchIndex=[],visible=[],lastLoadMs=null,overlayLoadMs=null;const images=new BoundedLRU(128,384*1024*1024),overlayCache=new BoundedLRU(96,32*1024*1024);modeSelect.value=state.renderMode;
const displayFloor=z=>7-z,rawZ=f=>7-f,worldToScreen=(x,y)=>[(x-state.x)*32*state.zoom+canvas.width/2,(y-state.y)*32*state.zoom+canvas.height/2],screenToWorld=(x,y)=>[(x-canvas.width/2)/(32*state.zoom)+state.x,(y-canvas.height/2)/(32*state.zoom)+state.y];
function syncUrl(){history.replaceState(null,'',viewUrl(location.href,state))}function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;draw()}addEventListener('resize',resize);
function loadImage(path){let image=images.get(path);if(image)return image;image=new Image;const start=performance.now();image.onload=()=>{lastLoadMs=performance.now()-start;images.set(path,image,image.naturalWidth*image.naturalHeight*4);draw()};image.src=path;images.set(path,image,0);return image}
async function loadOverlay(chunk){const key=`${chunk.z}/${chunk.chunkX}_${chunk.chunkY}`;let data=overlayCache.get(key);if(data)return data;const start=performance.now(),response=await fetch(`data/chunks/z${chunk.z}/${chunk.chunkX}_${chunk.chunkY}.json`);data=response.ok?await response.json():{};overlayLoadMs=performance.now()-start;overlayCache.set(key,data,JSON.stringify(data).length*2);draw();return data}
function markerId(kind,record){const p=record.position||record.entry||record.temple;return `${kind}:${record.name||record.actionId||record.uniqueId||record.houseId||record.serverId}:${p.x}:${p.y}:${p.z}`}
function showDetails(kind,record){state.selectedMarker=markerId(kind,record);syncUrl();details.hidden=false;details.innerHTML=`<button id="closeDetails" aria-label="Close details">×</button><h2>${record.name||kind}</h2><dl>${Object.entries(record).filter(([,v])=>v!==null&&typeof v!=='object').map(([k,v])=>`<dt>${k}</dt><dd>${String(v)}</dd>`).join('')}</dl><pre>${JSON.stringify(record,null,2)}</pre>`;$('#closeDetails').onclick=()=>{details.hidden=true;state.selectedMarker=null;syncUrl()}}
function viewportBounds(){const a=screenToWorld(0,0),b=screenToWorld(canvas.width,canvas.height);return [a[0],b[0],a[1],b[1]]}
function drawMarkers(){for(const chunk of visible){const key=`${chunk.z}/${chunk.chunkX}_${chunk.chunkY}`,data=overlayCache.get(key);if(!data){loadOverlay(chunk);continue}for(const kind of state.overlays)for(const record of data[kind]||[]){const p=record.position||record.entry||record.temple;if(!p||p.z!==state.z)continue;const [x,y]=worldToScreen(p.x+.5,p.y+.5);ctx.fillStyle=kind==='teleports'?'#00d8ff':kind==='monsterSpawns'?'#f04f4f':kind==='npcSpawns'?'#55df78':'#ffd24a';ctx.beginPath();ctx.arc(x,y,Math.max(4,6*state.zoom),0,Math.PI*2);ctx.fill();record._hit=[x,y,8];record._kind=kind;if(state.selectedMarker===markerId(kind,record)&&details.hidden)showDetails(kind,record)}}}
function draw(){if(!manifest)return;ctx.clearRect(0,0,canvas.width,canvas.height);const layer=baseLayer(state.renderMode,state.zoom);visible=visibleChunks(chunks,state.z,viewportBounds(),1);for(const c of visible){const [x,y]=worldToScreen(c.bounds[0],c.bounds[2]),w=c.imageWidth*state.zoom,h=c.imageHeight*state.zoom,path=layer==='detailed'?c.path:layer==='overview-low'?c.lowOverviewPath:c.overviewPath,image=loadImage(path);if(image.complete&&image.naturalWidth)ctx.drawImage(image,x,y,w,h)}drawMarkers();$('#coords').textContent=`X ${Math.floor(state.x)}  Y ${Math.floor(state.y)}  Floor ${displayFloor(state.z)}`;diagnostics.textContent=`Mode: ${state.renderMode}\nBase layer: ${layer}\nX/Y/Z: ${state.x.toFixed(1)} / ${state.y.toFixed(1)} / ${state.z}\nZoom: ${state.zoom.toFixed(3)}\nVisible chunks (+ margin): ${visible.length}\nImage cache: ${images.size}, approx ${(images.bytes/1048576).toFixed(1)} MiB / 384 MiB\nOverlay cache: ${overlayCache.size}, approx ${(overlayCache.bytes/1048576).toFixed(1)} MiB / 32 MiB\nEnabled overlays: ${state.overlays.length}${lastLoadMs===null?'':`\nRecent image load: ${lastLoadMs.toFixed(1)} ms`}${overlayLoadMs===null?'':`\nRecent overlay load: ${overlayLoadMs.toFixed(1)} ms`}`}
canvas.onpointerdown=e=>{drag=[e.clientX,e.clientY,state.x,state.y];canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{const [x,y]=screenToWorld(e.clientX*devicePixelRatio,e.clientY*devicePixelRatio);status.textContent=`X ${Math.floor(x)} Y ${Math.floor(y)} Floor ${displayFloor(state.z)}`;if(drag){state.x=drag[2]-(e.clientX-drag[0])*devicePixelRatio/(32*state.zoom);state.y=drag[3]-(e.clientY-drag[1])*devicePixelRatio/(32*state.zoom);draw()}};canvas.onpointerup=e=>{if(drag&&Math.hypot(e.clientX-drag[0],e.clientY-drag[1])<5){for(const entry of overlayCache.map.values())for(const [kind,records] of Object.entries(entry.value))if(Array.isArray(records))for(const r of records)if(r._hit&&Math.hypot(e.clientX*devicePixelRatio-r._hit[0],e.clientY*devicePixelRatio-r._hit[1])<=r._hit[2])return showDetails(kind,r)}drag=null;syncUrl()};canvas.onwheel=e=>{e.preventDefault();state.zoom=Math.max(.03,Math.min(4,state.zoom*Math.exp(-e.deltaY*.001)));syncUrl();draw()};
$('#zoomIn').onclick=()=>{state.zoom=Math.min(4,state.zoom*1.5);syncUrl();draw()};$('#zoomOut').onclick=()=>{state.zoom=Math.max(.03,state.zoom/1.5);syncUrl();draw()};floorSelect.onchange=()=>{state.z=+floorSelect.value;syncUrl();draw()};modeSelect.onchange=()=>{state.renderMode=persistMode(localStorage,history,location.href,modeSelect.value);draw()};$('#jump').onclick=()=>{state.x=+$('#x').value||state.x;state.y=+$('#y').value||state.y;if($('#z').value!=='')state.z=rawZ(Math.max(-8,Math.min(7,+$('#z').value)));floorSelect.value=state.z;syncUrl();draw()};$('#copy').onclick=()=>navigator.clipboard.writeText(`${Math.floor(state.x)},${Math.floor(state.y)},${displayFloor(state.z)}`);for(const box of document.querySelectorAll('[data-overlay]')){box.checked=state.overlays.includes(box.dataset.overlay);box.onchange=()=>{const set=new Set(state.overlays);box.checked?set.add(box.dataset.overlay):set.delete(box.dataset.overlay);state.overlays=[...set];localStorage.setItem('otheryn.atlas.layers',JSON.stringify(state.overlays));syncUrl();draw()}}$('#showDiagnostics').onchange=e=>{diagnostics.hidden=!e.target.checked};
$('#search').oninput=e=>{const q=e.target.value.trim().toLowerCase(),results=$('#searchResults');results.innerHTML='';if(q.length<2)return;for(const item of searchIndex.filter(v=>v.label.toLowerCase().includes(q)).slice(0,20)){const b=document.createElement('button');b.textContent=`${item.label} — ${item.kind}`;b.onclick=()=>{Object.assign(state,item.position);state.zoom=Math.max(state.zoom,.75);floorSelect.value=state.z;syncUrl();draw();results.innerHTML=''};results.append(b)}};
Promise.all([fetch('manifest.json').then(r=>r.json()),fetch('data/search-index.json').then(r=>r.ok?r.json():{records:[]})]).then(([m,s])=>{manifest=m;chunks=m.chunks;searchIndex=s.records;const floors=[...new Set(chunks.map(c=>c.z))].sort((a,b)=>displayFloor(a)-displayFloor(b));floorSelect.innerHTML=floors.map(v=>`<option value="${v}">${displayFloor(v)}</option>`).join('');floorSelect.value=state.z;status.textContent='Drag to pan / wheel to zoom';resize()});
