"""Write the dependency-free static atlas viewer."""
from pathlib import Path
import shutil
VIEWER_HTML='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Otheryn Maps</title><style>
html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#101215;color:#eee;font:14px system-ui}canvas{position:absolute;inset:0}button,select,input{background:#252a30;color:#eee;border:1px solid #66717d;border-radius:3px;padding:5px}button:focus-visible,input:focus-visible,select:focus-visible{outline:2px solid #4ec9ff}.panel{position:absolute;z-index:2;background:#171b20ed;border:1px solid #49515a;border-radius:7px;box-shadow:0 5px 22px #0008}.top{z-index:4;left:12px;right:12px;top:12px;padding:8px;display:flex;gap:7px;align-items:center}.controls{left:12px;top:68px;padding:9px;display:grid;gap:6px;max-height:calc(100% - 110px);overflow:auto}.controls label{display:flex;gap:5px;align-items:center}.search-wrap{position:relative;flex:1;max-width:420px}#search{width:100%;box-sizing:border-box}#searchResults{position:absolute;z-index:5;top:33px;width:100%;display:grid;background:#171b20;max-height:300px;overflow:auto}#searchResults button{text-align:left}#status{right:12px;bottom:12px;padding:6px}#details{right:12px;top:68px;width:min(360px,calc(100% - 24px));max-height:calc(100% - 100px);overflow:auto;padding:12px}#details pre{white-space:pre-wrap;font-size:11px}#details dt{color:#8fa0b2}#details dd{margin:0 0 5px}#diagnostics{white-space:pre;font:11px ui-monospace}#diagnostics[hidden],#details[hidden]{display:none}@media(max-width:700px){.top{flex-wrap:wrap}.controls{top:112px}.controls .layers{display:none}#details{top:auto;bottom:0;max-height:45%;width:auto;left:0;right:0}}
</style></head><body><canvas id="map" tabindex="0" aria-label="Interactive Otheryn world map"></canvas><header class="panel top"><strong>Otheryn Maps</strong><div class="search-wrap"><input id="search" aria-label="Search world" placeholder="Search NPC, monster, town, AID, UID…"><div id="searchResults"></div></div><span id="coords"></span><button id="copy" aria-label="Copy coordinates">Copy</button><button id="zoomOut" aria-label="Zoom out">−</button><button id="zoomIn" aria-label="Zoom in">+</button></header><aside class="panel controls"><label>Render mode <select id="renderMode"><option value="auto">Auto</option><option value="detailed">Detailed</option><option value="performance">Performance</option></select></label><label>Floor <select id="floor"></select></label><div><input id="x" type="number" placeholder="X"><input id="y" type="number" placeholder="Y"><input id="z" type="number" min="-8" max="7" placeholder="Floor"><button id="jump">Jump</button></div><div class="layers"><strong>Layers</strong><label><input type="checkbox" data-overlay="npcSpawns">NPCs</label><label><input type="checkbox" data-overlay="monsterSpawns">Monsters</label><label><input type="checkbox" data-overlay="teleports">Teleports</label><label><input type="checkbox" data-overlay="houses">Houses</label><label><input type="checkbox" data-overlay="houseDoors">House doors</label><label><input type="checkbox" data-overlay="actionIds">Action IDs</label><label><input type="checkbox" data-overlay="uniqueIds">Unique IDs</label><label><input type="checkbox" data-overlay="towns">Towns / temples</label><label><input type="checkbox" data-overlay="waypoints">Waypoints</label></div><label><input id="showDiagnostics" type="checkbox">Diagnostics</label><div id="diagnostics" hidden></div></aside><aside id="details" class="panel" hidden></aside><div id="status" class="panel">Loading manifest…</div><script type="module" src="viewer-app.js"></script></body></html>'''
VIEWER_HTML=VIEWER_HTML.replace('<label><input type="checkbox" data-overlay="waypoints">Waypoints</label>', '<label><input type="checkbox" data-overlay="waypoints">Waypoints</label><label><input type="checkbox" data-overlay="mechanics">Mechanics</label><label title="No authoritative boss classification is present"><input type="checkbox" disabled>Bosses (UNKNOWN)</label>')

def write_viewer(output:str|Path)->Path:
	root=Path(output);root.mkdir(parents=True,exist_ok=True);path=root/"index.html";path.write_text(VIEWER_HTML,encoding="utf-8",newline="\n")
	for source,target in (("viewer_runtime.js","viewer-runtime.js"),("viewer_app.js","viewer-app.js")):shutil.copyfile(Path(__file__).with_name(source),root/target)
	return path
