export const RENDER_MODES = new Set(['auto','detailed','performance']);
export const STORAGE_KEY = 'otheryn.atlas.renderMode';
export const DETAIL_SCALE = 1;
export const ENVIRONMENT_ANIMATION_SCALE = 1.5;
export function normalizeRenderMode(value){return RENDER_MODES.has(value)?value:null}
export function urlRenderMode(href){const u=new URL(href);const query=normalizeRenderMode(u.searchParams.get('render'));if(query)return query;const hash=new URLSearchParams(u.hash.replace(/^#/,''));return normalizeRenderMode(hash.get('render'))}
export function resolveRenderMode(href,stored){return urlRenderMode(href)||normalizeRenderMode(stored)||'auto'}
export function baseLayer(mode,scale){if(mode==='detailed'||(mode==='auto'&&scale>=DETAIL_SCALE))return 'detailed';return scale<0.25?'overview-low':'overview'}
export function modeUrl(href,mode){const u=new URL(href);u.searchParams.set('render',normalizeRenderMode(mode)||'auto');return u.toString()}
export function transitionState(state,mode){return {...state,renderMode:normalizeRenderMode(mode)||'auto'}}
export function persistMode(storage,history,href,mode){const value=normalizeRenderMode(mode)||'auto';storage.setItem(STORAGE_KEY,value);history.replaceState(null,'',modeUrl(href,value));return value}
export function parseViewState(href,fallback={}){const u=new URL(href),p=u.searchParams,out={...fallback};for(const key of ['x','y','z','zoom'])if(p.has(key)&&Number.isFinite(+p.get(key)))out[key]=+p.get(key);if(p.has('layers'))out.overlays=p.get('layers').split(',').filter(Boolean);if(p.has('marker'))out.selectedMarker=p.get('marker')||null;out.renderMode=resolveRenderMode(href,fallback.renderMode);return out}
export function parseCoordinateSearch(value){const match=/^\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*$/.exec(value);if(!match)return null;const [x,y,z]=match.slice(1).map(Number);return x<=65535&&y<=65535&&z<=15?{x,y,z}:null}
export function viewUrl(href,state){const u=new URL(href);for(const key of ['x','y','z','zoom'])if(Number.isFinite(state[key]))u.searchParams.set(key,String(state[key]));u.searchParams.set('render',normalizeRenderMode(state.renderMode)||'auto');if(state.overlays?.length)u.searchParams.set('layers',[...state.overlays].sort().join(','));else u.searchParams.delete('layers');if(state.selectedMarker)u.searchParams.set('marker',state.selectedMarker);else u.searchParams.delete('marker');return u.toString()}
export function visibleChunks(chunks,z,bounds,margin=1){return chunks.filter(c=>c.z===z&&c.logicalBounds[1]>=bounds[0]-margin*128&&c.logicalBounds[0]<=bounds[1]+margin*128&&c.logicalBounds[3]>=bounds[2]-margin*128&&c.logicalBounds[2]<=bounds[3]+margin*128)}
function addSupplementalControls(){if(typeof document==='undefined')return;const layers=document.querySelector('.layers');if(!layers||layers.querySelector('[data-overlay="supplementalNpcSpawns"]'))return;for(const [kind,label] of [['supplementalNpcSpawns','Supplemental NPCs'],['supplementalMonsterSpawns','Supplemental monsters']]){const row=document.createElement('label'),box=document.createElement('input');box.type='checkbox';box.dataset.overlay=kind;row.append(box,document.createTextNode(label));layers.append(row)}}
if(typeof document!=='undefined')addSupplementalControls();
export class BoundedLRU {constructor(maxEntries=128,maxBytes=384*1024*1024){this.maxEntries=maxEntries;this.maxBytes=maxBytes;this.map=new Map;this.bytes=0}get size(){return this.map.size}get(key){const v=this.map.get(key);if(!v)return null;this.map.delete(key);this.map.set(key,v);return v.value}set(key,value,bytes=0){this.delete(key);this.map.set(key,{value,bytes});this.bytes+=bytes;while(this.map.size>this.maxEntries||this.bytes>this.maxBytes){const oldest=this.map.keys().next().value;this.delete(oldest)}return value}delete(key){const v=this.map.get(key);if(!v)return false;this.bytes-=v.bytes;this.map.delete(key);return true}}
function stableOffset(record,total){let h=2166136261;const text=`${record.animationKey}:${record.position.x}:${record.position.y}:${record.position.z}`;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return total?Math.abs(h)%total:0}
function phaseFromOrder(order,d,value){const total=order.reduce((sum,i)=>sum+Math.max(1,d[i]||1),0);value=((value%total)+total)%total;for(const i of order){const duration=Math.max(1,d[i]||1);if(value<duration)return i;value-=duration}return order.at(-1)}
export function environmentPhase(record,elapsedMs){const d=record.phaseDurationsMs||[];if(!d.length)return 0;if(record.synchronized)return phaseFromOrder(d.map((_,i)=>i),d,elapsedMs);const start=(record.defaultStartPhase||0)%d.length,order=[],pingpong=record.loopType===-1||record.loopType>1;if(pingpong&&d.length>1){for(let i=start;i<d.length;i++)order.push(i);for(let i=d.length-2;i>=0;i--)order.push(i);for(let i=1;i<start;i++)order.push(i)}else for(let i=0;i<d.length;i++)order.push((start+i)%d.length);const total=order.reduce((sum,i)=>sum+Math.max(1,d[i]||1),0),value=elapsedMs+stableOffset(record,total);if(record.loopType===1&&record.loopCount>0&&value>=total*record.loopCount)return order.at(-1);return phaseFromOrder(order,d,value)}
function installEnvironmentAnimation(){if(typeof document==='undefined')return;const map=document.querySelector('#map');if(!map)return;const overlay=document.createElement('canvas');overlay.id='environmentAnimations';overlay.setAttribute('aria-hidden','true');Object.assign(overlay.style,{position:'absolute',inset:'0',pointerEvents:'none',zIndex:'1'});map.insertAdjacentElement('afterend',overlay);const ctx=overlay.getContext('2d'),images=new BoundedLRU(256,64*1024*1024),shards=new BoundedLRU(64,8*1024*1024),pending=new Set;ctx.imageSmoothingEnabled=false;let manifest=null,last=0;const image=path=>{let v=images.get(path);if(v)return v;v=new Image;v.onload=()=>images.set(path,v,v.naturalWidth*v.naturalHeight*4);v.src=path;images.set(path,v,0);return v};const loadShard=(z,x,y)=>{const key=`${z}/${x}_${y}`;if(shards.get(key)||pending.has(key))return;pending.add(key);fetch(`data/environment-animations/chunks/z${z}/${x}_${y}.json`).then(r=>r.ok?r.json():{records:[]}).then(v=>shards.set(key,v,JSON.stringify(v).length*2)).finally(()=>pending.delete(key))};const readState=()=>{const p=new URL(location.href).searchParams;return{x:+p.get('x')||32360,y:+p.get('y')||32230,z:Number.isFinite(+p.get('z'))?+p.get('z'):7,zoom:+p.get('zoom')||.18}};const paint=now=>{requestAnimationFrame(paint);if(document.hidden||now-last<80)return;last=now;if(overlay.width!==map.width||overlay.height!==map.height){overlay.width=map.width;overlay.height=map.height;overlay.style.width=map.clientWidth+'px';overlay.style.height=map.clientHeight+'px';ctx.imageSmoothingEnabled=false}ctx.clearRect(0,0,overlay.width,overlay.height);if(!manifest)return;const s=readState();if(s.zoom<ENVIRONMENT_ANIMATION_SCALE)return;const hx=overlay.width/(64*s.zoom),hy=overlay.height/(64*s.zoom),bounds=[s.x-hx,s.x+hx,s.y-hy,s.y+hy];for(const c of visibleChunks(manifest.chunks,s.z,bounds,0)){const key=`${c.z}/${c.chunkX}_${c.chunkY}`;loadShard(c.z,c.chunkX,c.chunkY);const data=shards.get(key);if(!data)continue;for(const r of data.records||[]){const p=r.position;if(!p||p.z!==s.z||p.x<bounds[0]-1||p.x>bounds[1]+1||p.y<bounds[2]-1||p.y>bounds[3]+1)continue;const x=(p.x+.5-s.x)*32*s.zoom+overlay.width/2,y=(p.y+.5-s.y)*32*s.zoom+overlay.height/2,size=32*s.zoom,u=image(r.underlay),clock=r.synchronized?Date.now():now,f=image(r.frames[environmentPhase(r,clock)]);if(u.complete&&u.naturalWidth)ctx.drawImage(u,x-size/2,y-size/2,size,size);if(f.complete&&f.naturalWidth)ctx.drawImage(f,x-size/2,y-size/2,size,size)}}};fetch('data/environment-animations/index.json').then(r=>r.ok?r.json():null).then(index=>index?.schemaVersion===1?fetch('manifest.json').then(r=>r.json()):null).then(value=>{manifest=value;requestAnimationFrame(paint)}).catch(()=>{})}
if(typeof document!=='undefined')queueMicrotask(installEnvironmentAnimation);
