"""Write the dependency-free static atlas viewer."""
from pathlib import Path
import shutil

VIEWER_HTML='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Otheryn Maps</title><style>
html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#101215;color:#eee;font:14px system-ui}canvas{position:absolute;inset:0}button,select,input{background:#252a30;color:#eee;border:1px solid #66717d;border-radius:3px;padding:5px}button:focus-visible,input:focus-visible,select:focus-visible,canvas:focus-visible{outline:2px solid #4ec9ff}canvas:focus-visible{outline-offset:-3px}.panel{position:absolute;z-index:2;background:#171b20ed;border:1px solid #49515a;border-radius:7px;box-shadow:0 5px 22px #0008}.top{z-index:4;left:12px;right:12px;top:12px;padding:8px;display:flex;gap:7px;align-items:center}.controls{left:12px;top:68px;padding:9px;display:grid;gap:6px;max-height:calc(100% - 110px);overflow:auto}.controls label{display:flex;gap:5px;align-items:center}.search-wrap{position:relative;flex:1;max-width:420px}#search{width:100%;box-sizing:border-box}#searchResults{position:absolute;z-index:5;top:33px;width:100%;display:grid;background:#171b20;max-height:300px;overflow:auto}#searchResults button{text-align:left}#status{right:12px;bottom:12px;padding:6px}#details{right:12px;top:68px;width:min(360px,calc(100% - 24px));max-height:calc(100% - 100px);overflow:auto;padding:12px}#details pre{white-space:pre-wrap;font-size:11px}#details dt{color:#8fa0b2}#details dd{margin:0 0 5px}#diagnostics{white-space:pre;font:11px ui-monospace}#diagnostics[hidden],#details[hidden]{display:none}@media(max-width:700px){.top{flex-wrap:wrap}.top button,.top input,.controls button,.controls input,.controls select{min-height:44px}.controls{top:112px}.controls .layers{display:none}#details{top:auto;bottom:0;max-height:45%;width:auto;left:0;right:0}}
</style></head><body><canvas id="map" tabindex="0" aria-label="Interactive Otheryn world map"></canvas><header class="panel top"><strong>Otheryn Maps</strong><div class="search-wrap"><input id="search" aria-label="Search world" placeholder="Search NPC, monster, town, AID, UID…"><div id="searchResults"></div></div><span id="coords"></span><button id="copy" aria-label="Copy coordinates">Copy</button><button id="zoomOut" aria-label="Zoom out">−</button><button id="zoomIn" aria-label="Zoom in">+</button></header><aside class="panel controls"><label>Render mode <select id="renderMode"><option value="auto">Auto</option><option value="detailed">Detailed</option><option value="performance">Performance</option></select></label><label>Z <select id="floor"></select></label><div><input id="x" type="number" placeholder="X"><input id="y" type="number" placeholder="Y"><input id="z" type="number" min="0" max="15" placeholder="Z"><button id="jump">Jump</button></div><div class="layers"><strong>Layers</strong><label><input type="checkbox" data-overlay="npcSpawns">NPCs</label><label><input type="checkbox" data-overlay="monsterSpawns">Monsters</label><label><input type="checkbox" data-overlay="teleports">OTBM teleports</label><label><input type="checkbox" data-overlay="scriptedTeleports">Scripted teleports</label><label><input type="checkbox" data-overlay="raidAreas">Raid / event areas</label><label><input type="checkbox" data-overlay="raidPointSpawns">Raid point spawns</label><label><input type="checkbox" data-overlay="npcServices">NPC services</label><label><input type="checkbox" data-overlay="verifiedBossSpawns">Verified bosses</label><label><input type="checkbox" data-overlay="houses">Houses</label><label><input type="checkbox" data-overlay="houseDoors">House doors</label><label><input type="checkbox" data-overlay="actionIds">Action IDs</label><label><input type="checkbox" data-overlay="uniqueIds">Unique IDs</label><label><input type="checkbox" data-overlay="towns">Towns / temples</label><label><input type="checkbox" data-overlay="waypoints">Waypoints</label></div><label><input id="tileInspector" type="checkbox">Tile inspector</label><label><input id="showDiagnostics" type="checkbox">Diagnostics</label><div id="diagnostics" hidden></div></aside><aside id="details" class="panel" aria-live="polite" hidden></aside><div id="status" class="panel" aria-live="off">Loading manifest…</div><script type="module" src="viewer-app.js"></script><script type="module" src="creature-animation-runtime.js"></script><script type="module" src="tile-inspector-runtime.js"></script><script type="module" src="accessibility-runtime.js"></script></body></html>'''
VIEWER_HTML=VIEWER_HTML.replace('<label><input type="checkbox" data-overlay="waypoints">Waypoints</label>', '<label><input type="checkbox" data-overlay="waypoints">Waypoints</label><label><input type="checkbox" data-overlay="mechanics">Mechanics</label>')
VIEWER_HTML=VIEWER_HTML.replace('</style>', '#tooltip,#tileInspectorTooltip{z-index:6;position:fixed;pointer-events:none;padding:5px 7px;font-size:12px;white-space:pre-line;max-width:min(340px,calc(100vw - 24px))}#tooltip[hidden],#tileInspectorTooltip[hidden]{display:none}html[data-reduced-motion=\"reduce\"] #environmentAnimations,html[data-reduced-motion=\"reduce\"] #creatureAnimations{animation:none}</style>')
VIEWER_HTML=VIEWER_HTML.replace('<body><canvas id="map" tabindex="0" aria-label="Interactive Otheryn world map"></canvas>', '<body><canvas id="map" tabindex="0" aria-label="Interactive Otheryn world map; arrow keys pan, plus/minus zoom, Page Up/Down change floor"></canvas><div id="tooltip" class="panel" role="tooltip" hidden></div><div id="tileInspectorTooltip" class="panel" role="tooltip" aria-live="polite" hidden></div>')
VIEWER_HTML=VIEWER_HTML.replace('placeholder="Search NPC, monster, town, AID, UID…"', 'placeholder="Search NPC, boss, raid, teleport, AID, UID, or X,Y,Z…"')


def write_viewer(output:str|Path)->Path:
	root=Path(output);root.mkdir(parents=True,exist_ok=True)
	path=root/"index.html";path.write_text(VIEWER_HTML,encoding="utf-8",newline="\n")
	for source,target in (("viewer_runtime.js","viewer-runtime.js"),("viewer_app.js","viewer-app.js"),("creature_animation_runtime.js","creature-animation-runtime.js"),("tile_inspector_runtime.js","tile-inspector-runtime.js"),("accessibility_runtime.js","accessibility-runtime.js")):shutil.copyfile(Path(__file__).with_name(source),root/target)
	return path
